permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

name: Ishita Mediratta
url: ishitamed19.github.io
enforce_ssl: ishitamed19.github.io
description: Ishita's personal website

collections:
  ml:
    output: true
  math:
    output: true

defaults:
  - scope:
      path: ""
      type: ml
    values:
      layout: post
  - scope:
      path: ""
      type: math
    values:
      layout: post
